# Mandatory variables:
baseURL: "/"
languageCode: "en-us"
title: "Pacio-decentralised semantic data with accounting and management"
subtitle: "Decentralised semantic data with accounting and management"
description: "Pacio is the applications platform for the decentralised era with semantic data plus built-in accounting and management"
author: 
    name: "David Hartley"
    email: "info@pacio.io"
copyright: "&copy; Pacio Core Ltd"

# Optional:
#
# GoogleAnalytics: # add  UA-nnn-nnnnnnnn ID and uncomment
enableGitInfo: false
summaryLength: 20
pygmentsUseClasses: true
pygmentsCodefencesGuessSyntax: true
pygmentsCodefences: true
paginate: 2  # put a higher, reasonable number


# Access in templates via $.Site.Params.somevalue ------------------------
params: 
    debug: false # cause template path to be output at top of page, handy for dev
    cssPath: 'css/main.css' # Default, override here
    only_feed_summaries: true
    fullname: "Pacio Blockchain"
    description: "The semantic decentralised data platform with built-in accounting and management"
    # Further customize logo in partials/logo.html; 
    # used in partials nav.html and footer.
    logotype: '<span><h1 class="is-size-3 has-text-weight-bold">Pacio</h1></span>'
        # Schema.org
    publisher:
        # Organization, Person
        type: Technology
        name: Pacio 
        #logo: url to logo image
# Primary Navigation Menu (partials/nav.html) ----------------------------
# Our exampleSite menu exploses About, Projects and Blog
# Note that "About" is added to the menu within content/about.md - it's 
# not a true "section" like post and project, although you can change this.

# NOTE: Don't put leading "/" in the url parameter
menu:
    sectionmenu:
        - name: "HOME"
          url: "/"
          weight: 10
        - name: "WHITEPAPER"
          url: "whitepaper/"
          identifier: "whitepaper"
          weight: 20
        - name: "DOCUMENTS"
          url: "documents/"
          identifier: "documents"
          weight: 30
        - name: "BLOG"
          url: "post/"
          weight: 40
        # Other single pages not within a section folder can be  
        # added to this menu in front matter of the document i.e. contact.md

# Syndication feeds atom.xml and rss.xml ---------------------------------
# Adds Atom feed support in conjunction with /layouts/index.atom.xml
# Change default rss filename to rss.xml, layout is built in to Hugo 
mediaTypes:
  application/atom:
    suffix: xml

outputFormats:
  Atom:
    mediaType: application/atom
    baseName: atom
  RSS:
    mediaType: application/rss
    baseName: rss

outputs:
  home:
    - HTML
    - Atom
    - RSS

# Optional, disable RSS feed
#disableKinds:
  #- RSS
